name: Build

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag:
        - cxx-Alpine
        - cxx-CentOS6 # CentOS 6 is EOL, so this image does not need to be rebuilt each time
        - cxx-Trusty
        - cxx-Xenial
        - Lucid-gcc
        - Precise-i386-gcc

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        cache-from: type=gha,scope=${{ matrix.tag }}
        cache-to: type=gha,mode=max,scope=${{ matrix.tag }}
        context: ${{ matrix.tag }}
        outputs: type=docker
        tags: 76eddge/build-images:${{ matrix.tag }}
        target: deploy

    - name: Login to DockerHub
      if: github.event_name == 'release'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: github.event_name == 'release'
      run: docker push -a 76eddge/build-images

    - name: Run Grype Scan
      if: github.event_name != 'release'
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/bin
        grype -o sarif '76eddge/build-images:${{ matrix.tag }}' > ${{ matrix.tag }}.sarif

    - name: Upload Grype Scan Results
      if: github.event_name != 'release'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ matrix.tag }}.sarif
        category: ${{ matrix.tag }}
